export const GOLD_AMM_ROUTER_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_mUSD", type: "address", internalType: "address" },
      { name: "_oracle", type: "address", internalType: "address" },
      { name: "_treasury", type: "address", internalType: "address" },
      { name: "_feeBps", type: "uint256", internalType: "uint256" },
      { name: "admin", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MARKET_OPERATOR_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyNo",
    inputs: [
      { name: "market", type: "address", internalType: "address" },
      { name: "collateralIn", type: "uint256", internalType: "uint256" },
      { name: "minAmountOut", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "buyYes",
    inputs: [
      { name: "market", type: "address", internalType: "address" },
      { name: "collateralIn", type: "uint256", internalType: "uint256" },
      { name: "minAmountOut", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "configFrozen",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "create",
    inputs: [
      { name: "title", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "resolutionSource", type: "string", internalType: "string" },
      { name: "duelKey", type: "bytes32", internalType: "bytes32" },
      { name: "isDynamic", type: "bool", internalType: "bool" },
      { name: "duration", type: "uint256", internalType: "uint256" },
      { name: "collateralIn", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "duelOracle",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract DuelOutcomeOracle" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "freezeConfig",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAllMarkets",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mUSD",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposerOutcome",
    inputs: [
      { name: "market", type: "address", internalType: "address" },
      { name: "_outcome", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "redeem",
    inputs: [
      { name: "market", type: "address", internalType: "address" },
      { name: "amountYes", type: "uint256", internalType: "uint256" },
      { name: "amountNo", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sellNo",
    inputs: [
      { name: "market", type: "address", internalType: "address" },
      { name: "tokenIn", type: "uint256", internalType: "uint256" },
      { name: "minAmountOut", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sellYes",
    inputs: [
      { name: "market", type: "address", internalType: "address" },
      { name: "tokenIn", type: "uint256", internalType: "uint256" },
      { name: "minAmountOut", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeConfig",
    inputs: [
      { name: "_treasury", type: "address", internalType: "address" },
      { name: "_feeBps", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleFromOracle",
    inputs: [{ name: "market", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleMarket",
    inputs: [{ name: "market", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "FeeConfigFrozen",
    inputs: [
      { name: "admin", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeConfigUpdated",
    inputs: [
      { name: "treasury", type: "address", indexed: true, internalType: "address" },
      { name: "feeBps", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MarketCreated",
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "market", type: "address", indexed: true, internalType: "address" },
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "title", type: "string", indexed: false, internalType: "string" },
      { name: "description", type: "string", indexed: false, internalType: "string" },
      { name: "resolutionSource", type: "string", indexed: false, internalType: "string" },
      { name: "deadline", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "liquidity", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;
